name: Build and Release Extension

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - name: Build Chrome Zip
        run: |
          rm -f dist/manifest.json
          cp manifest.json dist/manifest.json
          cd dist && zip -r ../chrome-extension.zip .
      - name: Build Firefox Zip
        run: |
          rm -f dist/manifest.json
          cp manifest.firefox.json dist/manifest.json
          cd dist && zip -r ../firefox-extension.zip .
      - name: Upload Chrome Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension
          path: chrome-extension.zip
      - name: Upload Firefox Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firefox-extension
          path: firefox-extension.zip
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            chrome-extension.zip
            firefox-extension.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
